spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db
spring.datasource.username=student
spring.datasource.password=chocolatefrog
telegram.bot.token=7966791801:AAGCtKqLkO2MDIhgryKtkbjQhfOrcNXOiis
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
